### ISSUE TITLE
linecache19 fails to build with Ruby 1.9.2

### ISSUE THREAD

**Issue by mistergibson** [mark-moseley/linecache#10]
gem install linecache19
ERROR:  Error installing linecache19:
    linecache19 requires Ruby version >= 1.9.2.

ruby -v
ruby 1.9.2dev (2010-07-02) [i486-linux]

not sure what the issue is here.

**Comment by mark-moseley** [comment]
Can you use a more recent version of 1.9.2?

**Comment by mistergibson** [comment]
Would you suggest doing a pull from the ruby repo here on github for fresh builds, or do you have a favorite?

**Comment by mark-moseley** [comment]
Try 1.9.2-p180 from ruby-lang.org.

**Comment by bogdan** [comment]
I am having the same problem with installing with RVM:

```
$ rvm use 1.9.2
Using /home/bogdan/.rvm/gems/ruby-1.9.2-p180
$ ruby -v
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-linux]
$ rvm exec gem install linecache19 --backtrace
gem install linecache19 --backtrace

rvm 1.6.20 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

ERROR:  Error installing linecache19:
    linecache19 requires Ruby version >= 1.9.2.
ERROR:  Error installing linecache19:
    linecache19 requires Ruby version >= 1.9.2.
Building native extensions.  This could take a while...
```

**Comment by invalidusrname** [comment]
I'm also seeing this problem. And why is my system rubygems being referenced when I'm using rvm?

```
$ rvm --version
rvm 1.6.25 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

$ rvm list
rvm rubies
=> ruby-1.9.2-p290 [ x86_64 ]

$ which ruby
/Users/mmcmahand/.rvm/rubies/ruby-1.9.2-p290/bin/ruby

$ bundle --version
Bundler version 1.0.15

$ bundle
…
Installing linecache19 (0.5.12) /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/installer.rb:163:in `install': linecache19 requires Ruby version >= 1.9.2.     (Gem::InstallError)
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/source.rb:100:in `install'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/rubygems_integration.rb:78:in `preserve_paths'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/source.rb:91:in `install'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/installer.rb:58:in `run'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/rubygems_integration.rb:93:in `with_build_args'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/installer.rb:57:in `run'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `each'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `each'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/installer.rb:49:in `run'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/installer.rb:8:in `install'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/cli.rb:222:in `install'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/vendor/thor/task.rb:22:in `send'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/vendor/thor/task.rb:22:in `run'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/vendor/thor.rb:246:in `dispatch'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/lib/bundler/vendor/thor/base.rb:389:in `start'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.15/bin/bundle:13
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/bin/bundle:19:in `load'
from /Users/mmcmahand/.rvm/gems/ruby-1.9.2-p290/bin/bundle:19
```

**Comment by troessner** [comment]
Any updates on this? Right now I can't use ruby-debug with ruby 1.9.2 which is a real pain in the ass....

**Comment by devn** [comment]
+1

To be clear, this is an issue on the current 1.9.2-head via RVM.

**Comment by fogonthedowns** [comment]
Gem::InstallError: linecache19 requires Ruby version >= 1.9.2.
An error occured while installing linecache19 (0.5.12), and Bundler cannot continue.
Make sure that `gem install linecache19 -v '0.5.12'` succeeds before bundling.
 apps2 ~/projects/sms/apps2/apps2_admin $ ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin10.8.0]
 apps2 ~/projects/sms/apps2/apps2_admin $

**Comment by ratbeard** [comment]
I was able to get this working.  Note, that I just switched to using `rbenv` instead of `rvm` to manage ruby versions.

My `bundle` command was pointed at the default, system wide bundler (`/usr/bin/bundle`) making it use the system ruby (187) even though I had set rbenv to use 192.  I removed the old bundler in a new shell using the default ruby: 

```
gem uninstall bundle   # then select all versions in menu
sudo rm /usr/bin/bundle  # this stuck around for some reason
```

Now my bundle command is pointed at my current rbenv ruby (192):

```
which bundle
/Users/mike.frawley/.rbenv/shims/bundle
```

**Comment by knuton** [comment]
Make sure to use a new shell session after installing `bundler` when using `rbenv`. Only after reading @ratbeard’s comment did I think of doing `which bundle` instead of `rbenv which bundle`.

I even suspect that @ratbeard’s solution helped because he started a new shell and that the other steps are not actually necessary (and you can and should keep your system wide bundler).
